### ISSUE TITLE
automap: no is not evaluated

### ISSUE THREAD

**Issue by cbu27** [mlsmithjr/transcoder#5]
I try to build a config with "automap: no" respectively "automap: False" but in the resulting ffmpeg command there is a "-map 0". 

My Config-Options:

```
  facebook:
      include: common
      automap: False
      output_options:
          - "-movflags +faststart"
          - "-vcodec libx264"
          - "-pix_fmt yuv420p"
          - "-preset:v slow"
          - "-profile:v main"
          - "-level 3.1"
          - "-crf 20"
          - "-coder 1"
          - "-flags +loop"
          - "-aspect 16:9"
          - "-r 25"
          - "-force_key_frames expr:gte(t,n_forced*4)"
          - "-vf movie=/tmp/sr_38.png[watermark];[in]yadif=0:0:0[deinterlaced];[deinterlaced]scale=size=1024x576:flags=lanczos:interl=0[scaled];[scaled][watermark]overlay=65:38[out]"
          - "-f mp4"
          - "-filter_complex [0:1]aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=mono[a1];[0:2]aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=mono[a2];[a1][a2]amerge=inputs=2,pan=stereo|c0<c0|c1<c1[aout]"
          - "-map 0:0"
          - "-map [aout]"
          - "-acodec libfdk_aac"
          - "-strict -2"
          - "-b:a 192k"
          - "-ac 2"
          - "-ar 48000"
```

The resulting command is:
`/root/bin/ffmpeg  -y -i /data/requests/XXX.mxf -movflags +faststart -vcodec libx264 -pix_fmt yuv420p -preset:v slow -profile:v main -level 3.1 -crf 20 -coder 1 -flags +loop -aspect 16:9 -r 25 -force_key_frames expr:gte(t,n_forced*4) -vf movie=/tmp/sr_38.png[watermark];[in]yadif=0:0:0[deinterlaced];[deinterlaced]scale=size=1024x576:flags=lanczos:interl=0[scaled];[scaled][watermark]overlay=65:38[out] -f mp4 -filter_complex [0:1]aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=mono[a1];[0:2]aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=mono[a2];[a1][a2]amerge=inputs=2,pan=stereo|c0<c0|c1<c1[aout] -map 0:0 -map [aout] -acodec libfdk_aac -strict -2 -b:a 192k -ac 2 -ar 48000 -map 0 /data/requests/xxx.mp4.tmp`

I think the last "-map 0" is too much.

Thank you.
